runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /index
  script: index.php
  
- url: /receipt
  script: receipt.php

- url: /tools
  script: tools.php

- url: /static
  static_dir: static